#!/usr/bin/env ruby
require 'optparse'
require './lib/spread'

#Setup ability to pass command line arguments neatly.
args = {}
OptionParser.new do |opt|
  opt.on('-i', '--input FILE', 'File to read') {
    |o| args[:input] = o
  }
  opt.on('-c', '--curve', 'Return bond curve') {
    |o| args[:curve] = o
  }
  opt.on('-b', '--benchmark', 'Return bond benchmark') {
    |o| args[:benchmark] = o
  }
end.parse!

if (args[:input])
  Spread.calculate(args)
else
  puts "Missing input file"
end
