#!/usr/bin/env ruby
require 'optparse'
require './lib/spread.rb'

#Setup ability to pass command line arguments neatly.
args = {}
OptionParser.new do |opt|
  opt.on('-i', '--input FILE', 'File to read') {
    |o| args[:input] = o
  }
  opt.on('-c', '--curve', 'Return bond curve') {
    |o| args[:curve] = true
  }
  opt.on('-b', '--benchmark', 'Return bond benchmark') {
    |o| args[:benchmark] = true
  }
end.parse!

#abort "Missing input or output file" unless (args[:file_in])

Spread.calculate(args)
